//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int id_fractura { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ITBIS { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
